name: data_models
description: A starting point for Dart libraries or applications.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  # Strumento per la generazione di codice
  build_runner: ^2.4.6
  # Generatore di codice per json_annotation
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
